"""
OASIS simulation manager
Manages parallel Twitter and Reddit simulations, driving the preset scripts
with configuration parameters generated by the LLM.
"""

import os
import re
import json
import shutil
from typing import Dict, Any, List, Optional
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

from ..config import Config
from ..utils.logger import get_logger
from .zep_entity_reader import ZepEntityReader, FilteredEntities
from .oasis_profile_generator import OasisProfileGenerator, OasisAgentProfile
from .simulation_config_generator import SimulationConfigGenerator, SimulationParameters
from ..utils.locale import t

logger = get_logger('sosim.simulation')

# A simulation id is always a single path segment. Ids reach this layer
# straight off a URL, so anything that could escape the data directory is
# rejected before it is joined to a path.
SIMULATION_ID_PATTERN = re.compile(r'^[A-Za-z0-9_-]{1,64}$')

# Explains a simulation left in 'preparing' by a backend restart. Preparation
# runs in a daemon thread, so the process dies without raising and no failure
# handler ever runs.
PREPARATION_INTERRUPTED_ERROR = (
    "Preparation was interrupted by a backend restart. "
    "Restart the simulation to prepare it again."
)


class SimulationBusyError(RuntimeError):
    """Raised when an operation is refused because the simulation is active."""


def validate_simulation_id(simulation_id: str) -> str:
    """Return the id unchanged, or raise when it is not a safe path segment."""
    if not isinstance(simulation_id, str) or not SIMULATION_ID_PATTERN.match(simulation_id):
        raise ValueError(f"Invalid simulation id: {simulation_id!r}.")
    return simulation_id


class SimulationStatus(str, Enum):
    """Simulation status"""
    CREATED = "created"
    PREPARING = "preparing"
    READY = "ready"
    RUNNING = "running"
    STOPPING = "stopping"
    PAUSED = "paused"
    STOPPED = "stopped"      # Stopped by hand
    COMPLETED = "completed"  # Finished on its own
    FAILED = "failed"


class PlatformType(str, Enum):
    """Platform type"""
    TWITTER = "twitter"
    REDDIT = "reddit"


@dataclass
class SimulationState:
    """Persisted simulation state"""
    simulation_id: str
    project_id: str
    graph_id: str

    # Enabled platforms
    enable_twitter: bool = True
    enable_reddit: bool = True

    # Status
    status: SimulationStatus = SimulationStatus.CREATED

    # Preparation results
    entities_count: int = 0
    profiles_count: int = 0
    entity_types: List[str] = field(default_factory=list)

    # Configuration generation
    profiles_generated: bool = False
    config_generated: bool = False
    config_reasoning: str = ""

    # Runtime data
    current_round: int = 0
    twitter_status: str = "not_started"
    reddit_status: str = "not_started"

    # Timestamps
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    updated_at: str = field(default_factory=lambda: datetime.now().isoformat())

    # Failure detail
    error: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        """Full state dictionary, used internally and on disk."""
        return {
            "simulation_id": self.simulation_id,
            "project_id": self.project_id,
            "graph_id": self.graph_id,
            "enable_twitter": self.enable_twitter,
            "enable_reddit": self.enable_reddit,
            "status": self.status.value,
            "entities_count": self.entities_count,
            "profiles_count": self.profiles_count,
            "entity_types": self.entity_types,
            "profiles_generated": self.profiles_generated,
            "config_generated": self.config_generated,
            "config_reasoning": self.config_reasoning,
            "current_round": self.current_round,
            "twitter_status": self.twitter_status,
            "reddit_status": self.reddit_status,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
            "error": self.error,
        }

    def get_default_platform(self) -> str:
        """Return the platform to use when the caller names none."""
        if self.enable_twitter and self.enable_reddit:
            return "reddit"  # Keep the historical default when both are on.
        elif self.enable_twitter:
            return "twitter"
        else:
            return "reddit"

    def to_simple_dict(self) -> Dict[str, Any]:
        """Reduced state dictionary, returned by the API."""
        return {
            "simulation_id": self.simulation_id,
            "project_id": self.project_id,
            "graph_id": self.graph_id,
            "status": self.status.value,
            "entities_count": self.entities_count,
            "profiles_count": self.profiles_count,
            "entity_types": self.entity_types,
            "profiles_generated": self.profiles_generated,
            "config_generated": self.config_generated,
            "error": self.error,
        }


class SimulationManager:
    """
    Simulation manager

    Responsibilities:
    1. Read and filter entities from the Zep knowledge graph.
    2. Generate OASIS agent profiles.
    3. Generate simulation configuration parameters with the LLM.
    4. Write every file the preset scripts need.
    """

    # Simulation data directory
    SIMULATION_DATA_DIR = os.path.join(
        os.path.dirname(__file__),
        '../../uploads/simulations'
    )

    # Terminal statuses a simulation may be deleted from without force.
    DELETABLE_STATUSES = {
        SimulationStatus.CREATED,
        SimulationStatus.READY,
        SimulationStatus.STOPPED,
        SimulationStatus.COMPLETED,
        SimulationStatus.FAILED,
    }

    def __init__(self):
        os.makedirs(self.SIMULATION_DATA_DIR, exist_ok=True)

        # In-memory cache of simulation states
        self._simulations: Dict[str, SimulationState] = {}

    def _get_simulation_dir(self, simulation_id: str, ensure: bool = True) -> str:
        """
        Return the data directory for a simulation.

        Args:
            simulation_id: Simulation ID
            ensure: Create the directory when it is missing. Read paths pass
                False so that a lookup for an unknown id cannot leave an empty
                directory behind.
        """
        validate_simulation_id(simulation_id)
        sim_dir = os.path.join(self.SIMULATION_DATA_DIR, simulation_id)
        if ensure:
            os.makedirs(sim_dir, exist_ok=True)
        return sim_dir

    def _save_simulation_state(self, state: SimulationState):
        """Write the simulation state to disk."""
        sim_dir = self._get_simulation_dir(state.simulation_id)
        state_file = os.path.join(sim_dir, "state.json")

        state.updated_at = datetime.now().isoformat()

        with open(state_file, 'w', encoding='utf-8') as f:
            json.dump(state.to_dict(), f, ensure_ascii=False, indent=2)

        self._simulations[state.simulation_id] = state

    def _load_simulation_state(self, simulation_id: str) -> Optional[SimulationState]:
        """Load the simulation state from disk, or from the cache."""
        if simulation_id in self._simulations:
            return self._simulations[simulation_id]

        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)
        state_file = os.path.join(sim_dir, "state.json")

        if not os.path.exists(state_file):
            return None

        with open(state_file, 'r', encoding='utf-8') as f:
            data = json.load(f)

        state = SimulationState(
            simulation_id=simulation_id,
            project_id=data.get("project_id", ""),
            graph_id=data.get("graph_id", ""),
            enable_twitter=data.get("enable_twitter", True),
            enable_reddit=data.get("enable_reddit", True),
            status=SimulationStatus(data.get("status", "created")),
            entities_count=data.get("entities_count", 0),
            profiles_count=data.get("profiles_count", 0),
            entity_types=data.get("entity_types", []),
            profiles_generated=data.get("profiles_generated", False),
            config_generated=data.get("config_generated", False),
            config_reasoning=data.get("config_reasoning", ""),
            current_round=data.get("current_round", 0),
            twitter_status=data.get("twitter_status", "not_started"),
            reddit_status=data.get("reddit_status", "not_started"),
            created_at=data.get("created_at", datetime.now().isoformat()),
            updated_at=data.get("updated_at", datetime.now().isoformat()),
            error=data.get("error"),
        )

        self._simulations[simulation_id] = state
        return state

    def create_simulation(
        self,
        project_id: str,
        graph_id: str,
        enable_twitter: bool = True,
        enable_reddit: bool = True,
    ) -> SimulationState:
        """
        Create a simulation.

        Args:
            project_id: Project ID
            graph_id: Zep knowledge graph ID
            enable_twitter: Run the Twitter platform
            enable_reddit: Run the Reddit platform

        Returns:
            SimulationState
        """
        import uuid
        simulation_id = f"sim_{uuid.uuid4().hex[:12]}"

        state = SimulationState(
            simulation_id=simulation_id,
            project_id=project_id,
            graph_id=graph_id,
            enable_twitter=enable_twitter,
            enable_reddit=enable_reddit,
            status=SimulationStatus.CREATED,
        )

        self._save_simulation_state(state)
        logger.info(f"Created simulation {simulation_id}, project={project_id}, graph={graph_id}")

        return state

    def prepare_simulation(
        self,
        simulation_id: str,
        simulation_requirement: str,
        document_text: str,
        defined_entity_types: Optional[List[str]] = None,
        use_llm_for_profiles: bool = True,
        progress_callback: Optional[callable] = None,
        parallel_profile_count: int = 3
    ) -> SimulationState:
        """
        Prepare the simulation environment, end to end.

        Steps:
        1. Read and filter entities from the Zep knowledge graph.
        2. Generate one OASIS agent profile per entity, optionally with the LLM
           and optionally in parallel.
        3. Generate the simulation configuration with the LLM: duration,
           activity level, posting frequency and so on.
        4. Write the configuration and profile files.

        Args:
            simulation_id: Simulation ID
            simulation_requirement: Simulation requirement, used by the LLM
            document_text: Source document text, used by the LLM as background
            defined_entity_types: Entity types to keep (optional)
            use_llm_for_profiles: Generate detailed personas with the LLM
            progress_callback: Progress callback (stage, progress, message)
            parallel_profile_count: Profiles generated in parallel, default 3

        Returns:
            SimulationState
        """
        state = self._load_simulation_state(simulation_id)
        if not state:
            raise ValueError(f"Simulation not found: {simulation_id}.")

        try:
            state.status = SimulationStatus.PREPARING
            state.error = None
            state.profiles_generated = False
            state.config_generated = False
            state.config_reasoning = ""
            self._save_simulation_state(state)

            sim_dir = self._get_simulation_dir(simulation_id)

            # ========== Stage 1: read and filter entities ==========
            if progress_callback:
                progress_callback("reading", 0, t('progress.connectingZepGraph'))

            reader = ZepEntityReader()

            if progress_callback:
                progress_callback("reading", 30, t('progress.readingNodeData'))

            filtered = reader.filter_defined_entities(
                graph_id=state.graph_id,
                defined_entity_types=defined_entity_types,
                enrich_with_edges=True
            )

            state.entities_count = filtered.filtered_count
            state.entity_types = list(filtered.entity_types)

            if progress_callback:
                progress_callback(
                    "reading", 100,
                    t('progress.readingComplete', count=filtered.filtered_count),
                    current=filtered.filtered_count,
                    total=filtered.filtered_count
                )

            if filtered.filtered_count == 0:
                state.status = SimulationStatus.FAILED
                state.error = (
                    "No matching entities were found. "
                    "Check that the knowledge graph was built correctly."
                )
                self._save_simulation_state(state)
                raise ValueError(state.error)

            # ========== Stage 2: generate agent profiles ==========
            total_entities = len(filtered.entities)

            if progress_callback:
                progress_callback(
                    "generating_profiles", 0,
                    t('progress.startGenerating'),
                    current=0,
                    total=total_entities
                )

            # The graph_id enables Zep retrieval, which gives the generator a
            # much richer context per entity.
            generator = OasisProfileGenerator(graph_id=state.graph_id)

            def profile_progress(current, total, msg):
                if progress_callback:
                    progress_callback(
                        "generating_profiles",
                        int(current / total * 100),
                        msg,
                        current=current,
                        total=total,
                        item_name=msg
                    )

            # Stream profiles to disk as they are generated, preferring the
            # Reddit JSON format.
            realtime_output_path = None
            realtime_platform = "reddit"
            if state.enable_reddit:
                realtime_output_path = os.path.join(sim_dir, "reddit_profiles.json")
                realtime_platform = "reddit"
            elif state.enable_twitter:
                realtime_output_path = os.path.join(sim_dir, "twitter_profiles.csv")
                realtime_platform = "twitter"

            profiles = generator.generate_profiles_from_entities(
                entities=filtered.entities,
                use_llm=use_llm_for_profiles,
                progress_callback=profile_progress,
                graph_id=state.graph_id,
                parallel_count=parallel_profile_count,
                realtime_output_path=realtime_output_path,
                output_platform=realtime_platform
            )

            state.profiles_count = len(profiles)
            state.profiles_generated = len(profiles) > 0
            self._save_simulation_state(state)

            # Write the profile files. Reddit was already streamed above; this
            # rewrite guarantees a complete file.
            if progress_callback:
                progress_callback(
                    "generating_profiles", 95,
                    t('progress.savingProfiles'),
                    current=total_entities,
                    total=total_entities
                )

            if state.enable_reddit:
                generator.save_profiles(
                    profiles=profiles,
                    file_path=os.path.join(sim_dir, "reddit_profiles.json"),
                    platform="reddit"
                )

            if state.enable_twitter:
                # OASIS requires CSV for Twitter, JSON for Reddit.
                generator.save_profiles(
                    profiles=profiles,
                    file_path=os.path.join(sim_dir, "twitter_profiles.csv"),
                    platform="twitter"
                )

            if progress_callback:
                progress_callback(
                    "generating_profiles", 100,
                    t('progress.profilesComplete', count=len(profiles)),
                    current=len(profiles),
                    total=len(profiles)
                )

            # ========== Stage 3: generate the simulation configuration ==========
            if progress_callback:
                progress_callback(
                    "generating_config", 0,
                    t('progress.analyzingRequirements'),
                    current=0,
                    total=3
                )

            config_generator = SimulationConfigGenerator()

            if progress_callback:
                progress_callback(
                    "generating_config", 30,
                    t('progress.callingLLMConfig'),
                    current=1,
                    total=3
                )

            sim_params = config_generator.generate_config(
                simulation_id=simulation_id,
                project_id=state.project_id,
                graph_id=state.graph_id,
                simulation_requirement=simulation_requirement,
                document_text=document_text,
                entities=filtered.entities,
                enable_twitter=state.enable_twitter,
                enable_reddit=state.enable_reddit
            )

            if progress_callback:
                progress_callback(
                    "generating_config", 70,
                    t('progress.savingConfigFiles'),
                    current=2,
                    total=3
                )

            config_path = os.path.join(sim_dir, "simulation_config.json")
            with open(config_path, 'w', encoding='utf-8') as f:
                f.write(sim_params.to_json())

            state.config_generated = True
            state.config_reasoning = sim_params.generation_reasoning

            if progress_callback:
                progress_callback(
                    "generating_config", 100,
                    t('progress.configComplete'),
                    current=3,
                    total=3
                )

            # The runner scripts stay in backend/scripts/ and are never copied
            # into the simulation directory; simulation_runner runs them there.

            state.status = SimulationStatus.READY
            self._save_simulation_state(state)

            logger.info(f"Prepared simulation {simulation_id}, "
                       f"entities={state.entities_count}, profiles={state.profiles_count}")

            return state

        except Exception as e:
            logger.error(f"Failed to prepare simulation {simulation_id}: {e}")
            import traceback
            logger.error(traceback.format_exc())
            state.status = SimulationStatus.FAILED
            state.error = str(e)
            self._save_simulation_state(state)
            raise

    def get_simulation(self, simulation_id: str) -> Optional[SimulationState]:
        """Return one simulation state, or None when it does not exist."""
        return self._load_simulation_state(simulation_id)

    def list_simulations(self, project_id: Optional[str] = None) -> List[SimulationState]:
        """List every simulation, newest first."""
        simulations = []

        if os.path.exists(self.SIMULATION_DATA_DIR):
            for sim_id in os.listdir(self.SIMULATION_DATA_DIR):
                # Skip hidden entries such as .DS_Store, and anything that is
                # not a directory.
                sim_path = os.path.join(self.SIMULATION_DATA_DIR, sim_id)
                if sim_id.startswith('.') or not os.path.isdir(sim_path):
                    continue
                if not SIMULATION_ID_PATTERN.match(sim_id):
                    continue

                state = self._load_simulation_state(sim_id)
                if state:
                    if project_id is None or state.project_id == project_id:
                        simulations.append(state)

        # os.listdir order is arbitrary, so sort here rather than leaving every
        # caller to discover that the list is unordered.
        simulations.sort(key=lambda s: s.created_at, reverse=True)
        return simulations

    def get_profiles(self, simulation_id: str, platform: str = None) -> List[Dict[str, Any]]:
        """Return the agent profiles generated for a simulation."""
        state = self._load_simulation_state(simulation_id)
        if not state:
            raise ValueError(f"Simulation not found: {simulation_id}.")

        if platform is None:
            platform = state.get_default_platform()

        if platform not in {"twitter", "reddit"}:
            raise ValueError(f"Unsupported platform: {platform}.")

        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)
        profile_path = os.path.join(
            sim_dir,
            "twitter_profiles.csv" if platform == "twitter" else "reddit_profiles.json",
        )

        if not os.path.exists(profile_path):
            return []

        if platform == "twitter":
            import csv

            with open(profile_path, 'r', encoding='utf-8', newline='') as f:
                return list(csv.DictReader(f))

        with open(profile_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    def get_simulation_config(self, simulation_id: str) -> Optional[Dict[str, Any]]:
        """Return the generated simulation configuration, or None."""
        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)
        config_path = os.path.join(sim_dir, "simulation_config.json")

        if not os.path.exists(config_path):
            return None

        with open(config_path, 'r', encoding='utf-8') as f:
            return json.load(f)

    def get_prepared_files(self, simulation_id: str) -> Dict[str, bool]:
        """Report which prepared files exist for a simulation."""
        state = self._load_simulation_state(simulation_id)
        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)

        expected = {"simulation_config.json": True}
        if state is None or state.enable_reddit:
            expected["reddit_profiles.json"] = True
        if state is None or state.enable_twitter:
            expected["twitter_profiles.csv"] = True

        return {
            filename: os.path.exists(os.path.join(sim_dir, filename))
            for filename in expected
        }

    def is_prepared(self, simulation_id: str) -> bool:
        """Report whether a simulation has everything a run needs."""
        state = self._load_simulation_state(simulation_id)
        if state is None or not state.config_generated:
            return False
        return all(self.get_prepared_files(simulation_id).values())

    def reconcile_preparations(self) -> List[Dict[str, Any]]:
        """
        Repair simulations left in 'preparing' by a backend restart.

        Preparation runs in a daemon thread inside Flask, so a restart kills it
        with no exception and neither failure handler runs. Nothing else moves
        such a simulation out of 'preparing', and every later start is refused
        with "Simulation not ready". Move each orphan to a resting state so the
        Simulations menu can restart it.

        Returns:
            One record per repaired simulation
        """
        repaired: List[Dict[str, Any]] = []

        for state in self.list_simulations():
            if state.status != SimulationStatus.PREPARING:
                continue

            if self.is_prepared(state.simulation_id):
                state.status = SimulationStatus.READY
                state.error = None
            else:
                state.status = SimulationStatus.FAILED
                state.error = PREPARATION_INTERRUPTED_ERROR
            self._save_simulation_state(state)

            repaired.append({
                "simulation_id": state.simulation_id,
                "previous_status": SimulationStatus.PREPARING.value,
                "status": state.status.value,
                "error": state.error,
            })
            logger.warning(
                "Reconciled an interrupted preparation: simulation_id=%s, status=%s",
                state.simulation_id,
                state.status.value,
            )

        return repaired

    def delete_simulation(
        self,
        simulation_id: str,
        force: bool = False,
    ) -> Dict[str, Any]:
        """
        Delete a simulation, its persisted state and its on-disk artifacts.

        The simulation is refused while it is active, so a running child process
        is never orphaned by a delete. With force the run is reaped first, which
        is what the menu's Delete offers on a row the user knows is stale.

        Args:
            simulation_id: Simulation ID
            force: Reap an active run instead of refusing the delete

        Returns:
            {"simulation_id", "deleted", "previous_status", "reaped_pid", "removed_dir"}

        Raises:
            ValueError: The simulation does not exist
            SimulationBusyError: The simulation is active and force is not set
        """
        from .simulation_runner import SimulationRunner

        validate_simulation_id(simulation_id)
        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)
        state = self._load_simulation_state(simulation_id)

        if state is None and not os.path.isdir(sim_dir):
            raise ValueError(f"Simulation not found: {simulation_id}.")

        previous_status = state.status.value if state else None
        activity = SimulationRunner.describe_activity(simulation_id)

        if activity["active"] and not force:
            raise SimulationBusyError(
                f"Simulation {simulation_id} is {activity['reason']}. "
                f"Stop it before deleting it, or delete it with force."
            )

        reaped_pid = None
        if activity["active"]:
            reaped_pid = SimulationRunner.reap_simulation(simulation_id)

        # A retained updater still owes Zep the tail of the run. Drain it before
        # the directory goes away rather than dropping accepted episodes.
        SimulationRunner.release_simulation(simulation_id)

        if os.path.isdir(sim_dir):
            shutil.rmtree(sim_dir)

        self._simulations.pop(simulation_id, None)

        logger.info(
            "Deleted simulation %s, previous status=%s, reaped pid=%s",
            simulation_id,
            previous_status,
            reaped_pid,
        )

        return {
            "simulation_id": simulation_id,
            "deleted": True,
            "previous_status": previous_status,
            "reaped_pid": reaped_pid,
            "removed_dir": sim_dir,
        }

    def get_run_instructions(self, simulation_id: str) -> Dict[str, str]:
        """Return the commands that run this simulation by hand."""
        sim_dir = self._get_simulation_dir(simulation_id, ensure=False)
        config_path = os.path.join(sim_dir, "simulation_config.json")
        scripts_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '../../scripts'))

        return {
            "simulation_dir": sim_dir,
            "scripts_dir": scripts_dir,
            "config_file": config_path,
            "commands": {
                "twitter": f"python {scripts_dir}/run_twitter_simulation.py --config {config_path}",
                "reddit": f"python {scripts_dir}/run_reddit_simulation.py --config {config_path}",
                "parallel": f"python {scripts_dir}/run_parallel_simulation.py --config {config_path}",
            },
            "instructions": (
                f"1. Activate the conda environment: conda activate SoSim\n"
                f"2. Run the simulation (the scripts live in {scripts_dir}):\n"
                f"   - Twitter only: python {scripts_dir}/run_twitter_simulation.py --config {config_path}\n"
                f"   - Reddit only: python {scripts_dir}/run_reddit_simulation.py --config {config_path}\n"
                f"   - Both platforms in parallel: python {scripts_dir}/run_parallel_simulation.py --config {config_path}"
            )
        }
